name: Abby Auto Redeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_XXXXXX" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
